### ISSUE TITLE
test wcs2:get-kvp-core-req42 in GetCoverage.xml allways fail.

### ISSUE THREAD

**Issue by coim32** [opengeospatial/ets-wcs20#10]
if condition in line 2232 of Getcoverage.xml is wrong, if deep-equal passes test fails.
it should be if boundedBy or domainSet or rangeType element is not equals test fails.

**Comment by jinsongdi123** [comment]
The CTL is updated accordingly.

**Comment by coim32** [comment]
change is not correct, see my comment
