### ISSUE TITLE
Testing wcs2:get-kvp-core-req1-9 fails with no explanation

### ISSUE THREAD

**Issue by coim32** [opengeospatial/ets-wcs20#102]
when I ran the test against my test server it just return
Error in call to extension function {public org.w3c.dom.NodeList com.occamlab.te.TECore.request(org.w3c.dom.Document,java.lang.String) throws java.lang.Throwable}: Exception in extension function java.lang.RuntimeException: Parser {http://www.occamlab.com/te/parsers}XMLValidatingParser threw an exception.
Result: Failed

**Comment by dstenger** [comment]
Thank you for reporting.

@keshav-nangare Can you please analyse the reported behavior?

**Comment by keshav-nangare** [comment]
@coim32 

Can you please provide service to analyze the reported behavior?

**Comment by coim32** [comment]
Is working now, I guess it could be a out of memory error that are common on teamengine
