### ISSUE TITLE
Run OGC WCS 2.0.1 core standard take hours and not finish

### ISSUE THREAD

**Issue by bangph** [opengeospatial/ets-wcs20#108]
I used http://cite.opengeospatial.org/teamengine/test.jsp on Chrome to run just WCS 2.0.1 core standard for this endpoint
http://conformance.rasdaman.com/rasdaman/ows?service=WCS&version=2.0.1&request=GetCapabilities

and it took more than 4 hours and still it haven't finished yet.

Now it is running at this test

`
 Testing wcs2:get-kvp-core-req33 type Mandatory in Test Mode with defaultResult Pass
`

![image](https://user-images.githubusercontent.com/6914451/156561933-e1fd4440-2cb8-48f7-bb71-75df5c686716.png)

@dstenger do you have any idea for speeding it up? I recall, a few years ago, it could finish in like < 1 hour.

**Comment by dstenger** [comment]
This issue is probably the reason for my previously mentioned problem reproducing the issue? #107
Is it possible to provide a service which can be used to reproduce the problem?

**Comment by bangph** [comment]
@dstenger I'm in my home country now (southest Asia), and http://cite.opengeospatial.org/teamengine/ is just not loadable after 10 minutes with error:

`502 Bad Gateway
nginx/1.18.0 (Ubuntu)`

As I cannot access teamengine webpage to recheck the problem of this ticket, so here is the endpoint for you, please check that:

http://conformance.rasdaman.com/rasdaman/ows?service=WCS&version=2.0.1&request=GetCapabilities

NOTE: this endpoint disabled the extra INSPIRE metadata which caused problem in teamengine in https://github.com/opengeospatial/ets-wcs20/issues/107

**Comment by bangph** [comment]
@dstenger FYI: Interestingly, http://cite.opengeospatial.org/te2/ is very fast to access. It should be the case as well for http://cite.opengeospatial.org/teamengine/ (not loadable)

**Comment by bangph** [comment]
@dstenger I'm testing endpoint http://conformance.rasdaman.com/rasdaman/ows?service=WCS&version=2.0.1&request=GetCapabilities on http://cite.opengeospatial.org/te2, will let you know if it can finish

**Comment by bangph** [comment]
@dstenger It works fast! Under few minutes to run test on beta teamengine http://cite.opengeospatial.org/te2/viewOldSessionLog.jsp?session=s0108. 

![image](https://user-images.githubusercontent.com/6914451/161887994-4522c2c3-b334-4bd4-a2e4-e602fd658a13.png)

Please check http://conformance.rasdaman.com/rasdaman/ows?service=WCS&version=2.0.1&request=GetCapabilities on http://cite.opengeospatial.org/teamengine/ as I cannot access to that.

**Comment by dstenger** [comment]
On http://cite.opengeospatial.org/teamengine/ it also took just a few minutes to run the tests with your service.
Can you please re-check if you can run the test suite on Production? If you still have problems, we have to check our infrastructure.

**Comment by bangph** [comment]
@dstenger thanks for rechecking. I can access to http://cite.opengeospatial.org/teamengine fast now and the tests run quickly which make me happy :).

It is much more better than I expected.
