### ISSUE TITLE
My WCS 2.0.1 service fails at the very beginning when run against compliance test

### ISSUE THREAD

**Issue by greatzzk** [opengeospatial/ets-wcs20#111]
Could you help analyze what is the problem?
http://52.55.216.140:6080/arcgis/services/mynetcdf/ImageServer/WCSServer?request=GetCapabilities&service=WCS
![image](https://user-images.githubusercontent.com/11200872/172971548-c669ab3f-a56b-432e-a340-d955f5f37ec9.png)

Test wcs2:main type Mandatory default result Passed (s0108)

Assertion: Prune query parameters if present.

Request d13242e33_1:
   Method: get
   URL: http://52.55.216.140:6080/arcgis/services/mynetcdf/ImageServer/WCSServer
Error in call to extension function {public org.w3c.dom.NodeList com.occamlab.te.TECore.request(org.w3c.dom.Document,java.lang.String) throws java.lang.Throwable}: Exception in extension function java.lang.RuntimeException: Parser {http://www.occamlab.com/te/parsers}XMLValidatingParser threw an exception.
Result: Failed

**Comment by dstenger** [comment]
Thank you for reporting.
Unfortunately, I am not able to access the provided test service to reproduce the reported behavior. Is it possible to make it available for me?

**Comment by dstenger** [comment]
I just tested the provided service against https://cite.ogc.org/teamengine/.

I am able to complete the test suite successfully and just the test wcs2:OWSCommon_exception fails four times:

```
Test wcs2:OWSCommon_exception type Mandatory default result Passed (s0015/d13242e65_1/d13242e193_1/d14560e333_1/d18331e669_1/d18331e3813_1)

Assertion: OWS common: test HTTP status codes for OGC Exceptions.

Message d14157e16_1:
   [FAILURE] Standard exception codes should be returned.

Result: Failed
```

Here, the wrong HTTP status code is returned by the service.

**Comment by greatzzk** [comment]
@dstenger i still cannot get a successful run against ogc team engine wcs 2.0.1 core. I will contact you privately for details. sending an email to (cite@lat-lon.de)

**Comment by dstenger** [comment]
Issue was solved offline. We identified an issue with the documentation:

![image001](https://user-images.githubusercontent.com/2989166/174609556-42c236d9-5e21-47c6-92ab-571a934241b1.png)
