### ISSUE TITLE
WCS 2.0.1 test on earth observation application profile has problem in Test wcseo:req6 

### ISSUE THREAD

**Issue by greatzzk** [opengeospatial/ets-wcs20#120]
the test fails and my server has:
![image](https://github.com/opengeospatial/ets-wcs20/assets/11200872/3f7138d5-b778-4452-bcce-7266c944366a)

the test is for checking:
https://cite.opengeospatial.org/te2/listings/te_base_scripts_wcs_2.0.1_ctl_eowcs_EO-data-model.html#wcseo:req6
all polygons listed in eop:EarthObservation/om:featureOfInterest/eop:Footprint element shall be contained in the bounding box of the gml:boundedBy element of the gml:Envelope

note: the spatial references are different. I suspect the test didn't perform reprojection before comparing?

**Comment by dstenger** [comment]
Thank you for reporting.

I agree that your assumption might be correct. Is it possible for you to change one of the CRS so that the same one is used to verify that?

**Comment by greatzzk** [comment]
@dstenger 
just to share some info that i feel important:
i read the specification and it says "the footprint is always given in WGS84". so i feel it will be good to convert the boundedby envelope to 4326 all the time before comparison.

**Comment by dstenger** [comment]
@bpross-52n Please use jts 1.13 (reference: https://github.com/opengeospatial/teamengine-bom/blob/main/pom.xml).

**Comment by greatzzk** [comment]
@bpross-52n @dstenger 
can we merge the PR so that we can test the updated te2? I still see it fails there

**Comment by dstenger** [comment]
We are currently working on other ets-wcs20 issues. As soon as we are finished, we will merge all pull requests and install a new revision of the test suite on Beta.
This is planned for late August/ September.

**Comment by greatzzk** [comment]
I verified on te2 against my server, cheers!!
