### ISSUE TITLE
wcs2:get-kvp-core-req12 fails

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wcs20#14]
wcs2:get-kvp-core-req12

Assertion: req12: For all WCS request types, test the request version parameter has     a fixed value of '2.0.1' by GetKVP.
Message d9183e2208_1: [MESSAGE] The server does not support the gml coverage.

Result: Failed

**Comment by dstenger** [comment]
Can you please provide more information?

**Comment by Vinni0803** [comment]
Log : 
 
Testing wcs2:get-kvp-core-req12 type Mandatory in Test Mode with defaultResult Pass (s0039/d9714e112_1/d9714e235_1/d1e91_1/d9183e108_1)...
             
    Assertion: req12: For all WCS request types, test the request version parameter has a fixed value of '2.0.1' by GetKVP.
       [FAILURE] The version in the wcs:Capabilities result should be "2.0.1".
       [MESSAGE] The server does not support the gml coverage.
       Test wcs2:get-kvp-core-req12 Failed

 Testing wcs2:post-xml-core-req12 type Mandatory in Test Mode with defaultResult Pass (s0039/d9714e112_1/d9714e235_1/d1e91_1/d9183e118_1)...
         

    Assertion: req12: For all WCS request types, test the request version parameter has a fixed value of '2.0.1' by PostXML.
    [ FAILURE] The version in the wcs:Capabilities result should be "2.0.1".
     [MESSAGE] the server does not support the gml coverage.
      Test wcs2:post-xml-core-req12 Failed

    And GetCapabilities request returns xml which contains three service type versions : 
     <ows:ServiceType codeSpace="OGC">OGC WCS</ows:ServiceType>
     <ows:ServiceTypeVersion>2.0.1</ows:ServiceTypeVersion>
     <ows:ServiceTypeVersion>1.1.1</ows:ServiceTypeVersion>
     <ows:ServiceTypeVersion>1.0.0</ows:ServiceTypeVersion>

**Comment by lgoltz** [comment]
@Vinni0803 Does the error still occur? Can you provide a service for testing?
From your comments above I see two failures:
1. The server does not support the gml coverage.
   * Occurs if the profile http://www.opengis.net/spec/GMLCOV/1.0/conf/gml is not supported
1. The version in the wcs:Capabilities result should be "2.0.1".
   * Occurs if the the version in the Capabilities document is not 2.0.1

**Comment by lgoltz** [comment]
I close this issue as the last comment is more then one year old.

@Vinni0803 If the problem still exists please reopen this issue and provide the URL of the service for testing.
