### ISSUE TITLE
Fix text in welcome page -  Instead of KVP should be POST

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wcs20#2]
Fix text in welcome page -  Instead of KVP should be POST
Welcome page:
http://cite.opengeospatial.org/te2/about/wcspost/1.0/web/

[Originally reported in the OGC CITE issue tracker: issue #879](https://portal.opengeospatial.org/services/srv_public_issues.php?call=viewIssue&issue_id=879)  

_Opened: 2013-10-24 15:36:40 Last Updated: 2013-10-31 10:02:30_

**Comment by bermud** [comment]
@jinsongdi123 please take a look at the welcome page and clarify what is available in the test. Thank you!

**Comment by jinsongdi123** [comment]
the text has been updated and uploaded to the wcs-exts branch
