### ISSUE TITLE
wcs2:req24 and wcs2:req41 failed due to incorrect response

### ISSUE THREAD

**Issue by keshav-nangare** [opengeospatial/ets-wcs20#20]
Failed tests:

Service URL: 
http://arcgis-ogcoregon-393577611.us-west-2.elb.amazonaws.com/arcgis/services/wcs201/GeoDataServer/WCSServer?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCapabilities

```

req24: When a WCS server encounters an error while performing a GetKVP DescribeCoverage operation it shall return an exception report message chosen as specified.
Result: Failed.


req41: When a WCS server encounters an error while performing a GetKVP GetCoverage operation it shall return an exception report message as specified.
Test HTTP status codes for OGC Exceptions.
Result: [FAILURE] Standard exception codes should be returned.


```

**Comment by keshav-nangare** [comment]
Solution for the Failed tests:


- req24 and req41:

 - The server returned the exception code with only one value i.e. exceptionCode="NoSuchCoverage", but test expects "status code" too.
 - The test expects two parameter in response status and exception code. Currently the server returns the only one "exceptionCode".
 - If the server returns the "status code" in the exception report (response), then this issue will resolved automatically.

Expected response:

For example:
```

Request d8928e2959_1:
   Method: get
   URL: http://ows.eox.at/cite/mapserver?service=WCS&VERSION=2.0.1&request=DescribeCoverage&CoverageId=CoverageId_Bogus
   Response from parser ctlp:HTTPParser:
      <response>
   <status code="404" protocol="HTTP/1.1">Not Found</status>
   <content>
      <ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/2.0"
                           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                           version="2.0.1"
                           xml:lang="en-US"
                           xsi:schemaLocation="http://www.opengis.net/ows/2.0 http://schemas.opengis.net/ows/2.0/owsExceptionReport.xsd">
         <ows:Exception exceptionCode="NoSuchCoverage" locator="coverage">
            <ows:ExceptionText>msWCSDescribeCoverage20(): WCS server error. Unknown coverage: (CoverageId_Bogus)</ows:ExceptionText>
         </ows:Exception>
      </ows:ExceptionReport>
   </content>
```

**Comment by lgoltz** [comment]
@keshav-nangare Can you please recheck this issue? Does the failure still occur? Both tests wraps some other tests. Which are the failing tests? The service is not longer available.

**Comment by keshav-nangare** [comment]
> Service URL:
http://arcgis-ogcoregon-393577611.us-west-2.elb.amazonaws.com/arcgis/services/wcs201/GeoDataServer/WCSServer?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCapabilities

Currently, the above service is not available so we cannot reproduce this issue.

The issue is not reproducible so we can close this for now.

The test **` wcs2:req24`** and **`wcs2:req41`** executed successfully with below RI.

RI [1] http://ows.eox.at/cite/mapserver?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCapabilities

**Comment by lgoltz** [comment]
@keshav-nangare Thanks, Ii will close this issue.
