### ISSUE TITLE
[Critical]ext_crs wrong input parameters (Capabilities,SupportsGML)  from calling in wcs2main.xml

### ISSUE THREAD

**Issue by bangph** [opengeospatial/ets-wcs20#22]
This problem is critical as it makes CRS extension test failed badly, because ext_crs.xml does not know the passed parameter to run the test
`
  <ctl:test name="wcs2:crs">
    <ctl:param name="url"/>
    <ctl:param name="Capabilities"/>
    <ctl:param name="SupportsGML" />`

Meanwhile in wcs2main.xml, it only calls this test suite with "url" parameter

`<xsl:when test="contains($ext_crs,'crs')">
							<ctl:call-test name="wcs2:crs">
								<ctl:with-param name="url" select="$url"/>
							</ctl:call-test>`

I'm not sure why ext_crs instead of having a GetCapabilities internally as same as other test suite (e.g: ext-get-scal.xml as it will get the value for the local variable "Capabilities" on the top of the file), in ext_crs, it try to do an irrelevant request with DescribeCoverage ???)

`<ctl:url>
								<xsl:value-of select="$url"/>
							</ctl:url>
							<ctl:method>get</ctl:method>
							<ctl:param name="service">WCS</ctl:param>
							<ctl:param name="VERSION">2.0.1</ctl:param>           
							<ctl:param name="request">DescribeCoverage</ctl:param>      
							<ctl:param name="coverageid"><xsl:value-of select="$Capabilities//*[local-name()='CoverageSummary'][1]/*[local-name()='CoverageId'][1]"/></ctl:param>   `

Please fix it as soon as possible.

**Comment by bangph** [comment]
I'd suggest it can be fixed like this (old and new crs test suite) https://www.diffchecker.com/BR1g6y9j.

@bermud

**Comment by bangph** [comment]
I update the diff here, can you please consider https://www.diffchecker.com/BR1g6y9j

@bermud @keshav-nangare

**Comment by keshav-nangare** [comment]
Updated the correct input parameters for ext_crs test as suggested by Bang.

Fixed with this commit: 9acd37ed9a01b0c87058d97ce0f2ac91161c15d1 [ PR #51 ].
