### ISSUE TITLE
Update user form to match correct names for conformance classes

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wcs20#25]
![image](https://cloud.githubusercontent.com/assets/3738898/20567234/fdb3cc00-b165-11e6-83d6-5580f32852ba.png)

Also make sure that the test have the attributes that explicitly say which ones are the core and which ones are the conformance classes.

Core should be the default and should not be checked.

**Comment by keshav-nangare** [comment]
Updated the user form with the correct conformance class names.

Fixed with this commit:  d001aa8930663a7fba60ebd9945ae99ccb789e4b
