### ISSUE TITLE
TBD tests in official suites

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wcs20#3]
I noticed that there are several ToBeDone's (grep TBD) in WCS testsuite,
especially on SOAP requests. These tests are actually run and give a green
light in the final results, but they are not evaluated in practice.
[Originally reported in the OGC CITE issue tracker: issue #911](https://portal.opengeospatial.org/services/srv_public_issues.php?call=viewIssue&issue_id=911)  

Entered by: Meissl, Stephan

_Opened: 2013-12-05 16:33:48 Last Updated: 2013-12-16 10:07:59_

**Comment by bermud** [comment]
I suggest:
- remove  TBD "faked' tests. 
- create an issue related to what needs to be done related to SOAP,  for remembering/managing purposes. 
What do you all think @Schpidi @jinsongdi123

**Comment by jinsongdi123** [comment]
The TBD has been removed.
The SOAP for GetCoverage will be done after the update of SOAP extension.

**Comment by pebau** [comment]
thanks, Jin!
-Peter

On 02/21/2015 10:44 AM, jinsongdi123 wrote:
>
> The TBD has been removed.
> The SOAP for GetCoverage will be done after the update of SOAP extension.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opengeospatial/ets-wcs20/issues/3#issuecomment-75364250>.
>

-- 
Dr. Peter Baumann
 - Executive Director, rasdaman GmbH Bremen (HRB 26793)
   www.rasdaman.com, mail: baumann@rasdaman.com
   tel: 0800-rasdaman, fax: 0800-rasdafax, mobile: +49-173-5837882
 - Professor of Computer Science, Jacobs University Bremen
   www.faculty.jacobs-university.de/pbaumann
   mail: p.baumann@jacobs-university.de
   tel: +49-421-200-3178, fax: +49-421-200-493178
"A brilliant idea is a job halfdone."
