### ISSUE TITLE
WCS 2.0.1 - Inconsistence between WCS Core and WCS Scaling Extension requirement

### ISSUE THREAD

**Issue by bangph** [opengeospatial/ets-wcs20#37]
So to test WCS 2.0.1 Core and Scale Extension, it needs to import some coverage to the entry service (at least: 2 types of coverage for WCS Core: 

> <CoverageSummary><CoverageId>test_mean_summer_airtemp</CoverageId><CoverageSubtype>RectifiedGridCoverage</CoverageSubtype>

> <CoverageId>test_mr</CoverageId>
<CoverageSubtype>GridCoverage</CoverageSubtype>

then WCS Core can pass without any error. But WCS Scale Extension will have 1 error in  Test wcs2:get-scal-req3-kvp 
> Message d1506e783_1:
   [FAILURE] The service should offer at least one ReferenceableGridCoverage.

However, if add one ReferenceableGridCoverage before testing WCS Core, WCS Scale, e.g:
> <CoverageId>test_z_irr_cube_2</CoverageId><CoverageSubtype>ReferenceableGridCoverage</CoverageSubtype>

then WCS Core will failed due to ReferenceableGridCoverage **only exists in GML 3.3 (not GML 3.2.1 and the schema validation is error)**.

Message d8936e2013_1:
   [FAILURE] The response to a successful PostXML DescribeCoverage request with n>0 coverage identifiers shall be a list containing n items.

Request d8936e2023_1:
   Method: get
   URL: http://kahlua.eecs.jacobs-university.de/conformance?service=WCS&VERSION=2.0.1&request=DescribeCoverage&CoverageId=test_mean_summer_airtemp,test_z_irr_cube_2
   Response from parser ctlp:XMLValidatingParser:
      
   Messages from parser ctlp:XMLValidatingParser:
        Validation error:
  cvc-complex-type.2.4.a: Invalid content was found starting with element 'gmlrgrid:ReferenceableGridByVectors'. One of '{"http://www.opengis.net/gml/3.2":AbstractGeometry, "http://www.opengis.net/gml/3.2":AbstractTimeObject}' is expected.
1 validation error detected.

> Message d8936e2075_1:
   [FAILURE] The response to a successful PostXML DescribeCoverage request with n>0 coverage identifiers shall be a list containing n items.

Result: Failed

So It should be best to remove the requirement in Scale test for ReferenceableGridCoverage if WCS 2.0.1 will not use GML 3.3.

**Comment by bangph** [comment]
@bermud @keshav-nangare

**Comment by eshirschorn** [comment]
ReferenceableGridCoverage does not exist in GML 3.2.1.  It exists only in GMLCOV 1.0 (renamed recently to CIS 1.0).  Such disharmony issues are cleaned up via the candidate extension standard OGC 16-083r2, the CIS 1.0 ReferenceableGridCoverage Extension.  It is a proper extension of CIS 1.0 and contains the 3 referenceable grid elements of GML 3.3 plus a 4th referenceable grid element for sensor model support via SensorML 2.0.  Voting by the OGC TC will be completed on April 3, 2017.

**Comment by bangph** [comment]
@eshirschorn: The CIS is accepted by OGC, but these test will stay for long times for WCS 2.0.1, so for now, I could not run CITE test for WCS 2.0.1 combinations in one session (core, processcoverages, rangesubset and scale), but, 2 sessions (scale and another session for the rest of WCS extensions).

**Comment by lgoltz** [comment]
@bangph Can you please check if the error still occurs? 
I've tested with TEAM Engine 4.10 and ETS Web Coverage Service (WCS) 2.0.1 (1.12) [1] and the service [1] (with the workaround described in https://github.com/opengeospatial/ets-wcs20/issues/43#issuecomment-340423924)

The test  `wcs2:get-scal-req3-kvp` is successful. 

[1] http://cite.opengeospatial.org/teamengine/
[2] http://moon.planetserver.eu:8084/rasdaman/ows?service=WCS&request=GetCapabilities&acceptversions=2.0.1

**Comment by bangph** [comment]
@lgoltz this is different problem, you can see https://github.com/opengeospatial/ets-wcs20/issues/37#issuecomment-289619727

Basically, WCS 2.0.1 core does not support a ReferenceableGridCoverage but WCS 2.0.1 Scaling Extension wants to have one of this coverage type to test, which means, normally, I have to run test for WCS 2.0.1 core without test for Scaling and after that I will only run test Scaling extension from my work around in https://github.com/opengeospatial/ets-wcs20/issues/43#issuecomment-340423924.

**Comment by lgoltz** [comment]
@bangph  Thanks for clarification, I think I understand the problem now. 
In the CTL scripts  a can see that the test `wcs2:get-scal-req3-kvp` fails if a ReferenceableGridCoverage is not provided. 

Which test fails in WCS 2.0.1 CORE if the ReferenceableGridCoverage is provided? Several test can fail with the message `The response to a successful PostXML DescribeCoverage request with n>0 coverage identifiers shall be a list containing n items`.
The GMLCOV 1.0 is already part of the project. Maybe we can enhance the validation to avoid the validation failure instead of removing (or simplifying) the test in SCALE EXT.

**Comment by pebau** [comment]
Likely the ReferenceableGridCoverage branch needs to be revisited in completeness - recently the "OGC Coverage Implementation Schema - ReferenceableGridCoverage Extension" [1] has been adopted. Maybe it's good to involve the spec editor,  Eric Hirschorn, in discussions about a corresponding ETS for the new spec (that also would solve the issue discussed here I believe).

[1] http://docs.opengeospatial.org/is/16-083r2/16-083r2.html

**Comment by ghobona** [comment]
@bangph  Is this Issue still valid? 

If so, could you please provide a link to a service so that we can reproduce the issue?

**Comment by bangph** [comment]
@ghobona this issue after 6 years is still there because WCS 2.0.1 core doesn't support ReferenceableGridCoverage coverage type.

Here is the endpoint http://conformance.rasdaman.com/rasdaman/ows?service=WCS&version=2.0.1&request=GetCapabilities which has test_irr_cube_1 coverage as ReferenceableGridCoverage.

The only solution here is as written 6 years ago is:

>  remove the requirement in Scale test for ReferenceableGridCoverage

**Comment by bpross-52n** [comment]
@bangph Just to be sure, if we would remove the requirement in Scale test for ReferenceableGridCoverage, you would have to remove the ReferenceableGridCoverage from the WCS, so that the core tests would also pass, right?

**Comment by bangph** [comment]
@bpross-52n even if you don't remove Scale test for ReferenceableGridCoverage (this exists in WCS Scaling extension) when I test WCS core, I still need to remove this testing ReferenceableGridCoverage coverage.

**Comment by dstenger** [comment]
Thanks for the quick feedback.
So, the value of your proposed fix (remove the requirement in Scale test for ReferenceableGridCoverage) would be that you can remove ReferenceableGridCoverage and then pass both, Core and WCS Scaling extension, in the same test run?

**Comment by bangph** [comment]
@bpross-52n yes, correct, the idea of this ticket is to allow to pass core and Scaling extensions in the same run.
