### ISSUE TITLE
The req21 and req22 are failed with the OSGeo(MapServer) Server

### ISSUE THREAD

**Issue by keshav-nangare** [opengeospatial/ets-wcs20#38]
The server URL: http://ows.eox.at/cite/mapserver?service=wcs&version=2.0.1&request=getcapabilities

WCS20 Test version : 1.12-SNAPSHOT
Teamengine: 4.10

I have executed the only "WCS Core" with above URL.

## **The test wcs2:get-kvp-core-req21 failed**

```
Request d427e2023_1:
   Method: get
   URL: http://ows.eox.at/cite/mapserver?service=WCS&VERSION=2.0.1&request=DescribeCoverage&CoverageId=MER_FRS_1PNUPA20090701_124435_000005122080_00224_38354_6861_RGB,MER_FRS_1PNUPA20090701_124435_000005122080_00224_38354_6861_RGB
   Response from parser ctlp:XMLValidatingParser:
      
   Messages from parser ctlp:XMLValidatingParser:
        Validation error:
  cvc-id.2: There are multiple occurrences of ID value 'MER_FRS_1PNUPA20090701_124435_000005122080_00224_38354_6861_RGB'.
Validation error:
  cvc-attribute.3: The value 'MER_FRS_1PNUPA20090701_124435_000005122080_00224_38354_6861_RGB' of attribute 'gml:id' on element 'wcs:CoverageDescription' is not valid with respect to its type, 'ID'.
Validation error:
  cvc-id.2: There are multiple occurrences of ID value 'grid_MER_FRS_1PNUPA20090701_124435_000005122080_00224_38354_6861_RGB'.
Validation error:
  cvc-attribute.3: The value 'grid_MER_FRS_1PNUPA20090701_124435_000005122080_00224_38354_6861_RGB' of attribute 'gml:id' on element 'gml:RectifiedGrid' is not valid with respect to its type, 'ID'.
Validation error:
  cvc-id.2: There are multiple occurrences of ID value 'grid_origin_MER_FRS_1PNUPA20090701_124435_000005122080_00224_38354_6861_RGB'.
Validation error:
  cvc-attribute.3: The value 'grid_origin_MER_FRS_1PNUPA20090701_124435_000005122080_00224_38354_6861_RGB' of attribute 'gml:id' on element 'gml:Point' is not valid with respect to its type, 'ID'.
6 validation errors detected.


Message d427e2075_1:
   [FAILURE] The response to a successful PostXML DescribeCoverage request with n>0 coverage identifiers shall be a list containing n items.

Result: Failed
```
## Test wcs2:post-xml-core-req21 failed:

```
Request d427e1889_1:
   Method: post
   URL: http://ows.eox.at/cite/mapserver
   Body: 
<?xml version="1.0" encoding="UTF-8"?>
							<wcs:DescribeCoverage  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    								xmlns:wcs='http://www.opengis.net/wcs/2.0'
    								xmlns:gml='http://www.opengis.net/gml/3.2'
    								xsi:schemaLocation='http://www.opengis.net/wcs/2.0 http://schemas.opengis.net/wcs/2.0/wcsAll.xsd'
    								service="WCS" version="2.0.1">
    								<wcs:CoverageId>MER_FRS_1PNUPA20090701_124435_000005122080_00224_38354_6861_RGB</wcs:CoverageId><wcs:CoverageId>MER_FRS_1PNUPA20090701_124435_000005122080_00224_38354_6861_RGB</wcs:CoverageId></wcs:DescribeCoverage>
   Response from parser ctlp:XMLValidatingParser:
      
   Messages from parser ctlp:XMLValidatingParser:
        Validation error:
  cvc-id.2: There are multiple occurrences of ID value 'MER_FRS_1PNUPA20090701_124435_000005122080_00224_38354_6861_RGB'.
Validation error:
  cvc-attribute.3: The value 'MER_FRS_1PNUPA20090701_124435_000005122080_00224_38354_6861_RGB' of attribute 'gml:id' on element 'wcs:CoverageDescription' is not valid with respect to its type, 'ID'.
Validation error:
  cvc-id.2: There are multiple occurrences of ID value 'grid_MER_FRS_1PNUPA20090701_124435_000005122080_00224_38354_6861_RGB'.
Validation error:
  cvc-attribute.3: The value 'grid_MER_FRS_1PNUPA20090701_124435_000005122080_00224_38354_6861_RGB' of attribute 'gml:id' on element 'gml:RectifiedGrid' is not valid with respect to its type, 'ID'.
Validation error:
  cvc-id.2: There are multiple occurrences of ID value 'grid_origin_MER_FRS_1PNUPA20090701_124435_000005122080_00224_38354_6861_RGB'.
Validation error:
  cvc-attribute.3: The value 'grid_origin_MER_FRS_1PNUPA20090701_124435_000005122080_00224_38354_6861_RGB' of attribute 'gml:id' on element 'gml:Point' is not valid with respect to its type, 'ID'.
6 validation errors detected.


Message d427e1934_1:
   [FAILURE] The response to a successful PostXML DescribeCoverage request with n>0 coverage identifiers shall be a list containing n items.

Result: Failed
```

Similarly the Test `wcs2:get-kvp-core-req22` and Test `wcs2:post-xml-core-req22` are Failed

**Comment by bermud** [comment]
@Schpidi can you please help us figure out what the issue is? Thank you!

**Comment by lgoltz** [comment]
The validation errors are fine, the response contains the CoverageDesription of the same Coverage two times. This leads to the same gml:ids two times which is invalid GML. 

The request contains the same CoveragId  two times: http://ows.eox.at/cite/mapserver?service=WCS&VERSION=2.0.1&request=DescribeCoverage&CoverageId=MER_FRS_1PNUPA20090701_124435_000005122080_00224_38354_6861_RGB,MER_FRS_1PNUPA20090701_124435_000005122080_00224_38354_6861_RGB

It must be checked why the same CoverageId is requested two times in the same request. In the cabapilities only one CoverageSummary is provided: http://ows.eox.at/cite/mapserver?service=wcs&version=2.0.1&request=getcapabilities

**Comment by keshav-nangare** [comment]
@lgoltz 

The DescribeCoverage request has the two hard-coded XPath i.e. first coverage_Id and last coverage_id that's why the same coverage_id is appearing in request twice.

Here is the line of code: 
https://github.com/opengeospatial/ets-wcs20/blob/aada53aaf909b67e169ba0f618732215508e9aa5/src/main/scripts/ctl/DescribeCoverage.xml#L1158
```
<ctl:param name="CoverageId">
	<xsl:value-of select="concat($Capabilities//*[local-name()='CoverageSummary'][1]/*[local-name()='CoverageId'][1],',')"/>
	<xsl:value-of select="$Capabilities//*[local-name()='CoverageSummary'][last()]/*[local-name()='CoverageId']"/>
</ctl:param>
```

I will update this request as similar to other describeCoverage requests. 
https://github.com/opengeospatial/ets-wcs20/blob/aada53aaf909b67e169ba0f618732215508e9aa5/src/main/scripts/ctl/DescribeCoverage.xml#L1124

**Comment by keshav-nangare** [comment]
@lgoltz 

I have tested this changes and test Req21: `wcs2:post-xml-core-req21`  and `wcs2:get-kvp-core-req21` is failing with the below error message.

`[FAILURE] The response to a successful PostXML DescribeCoverage request with n>0 coverage identifiers shall be a list containing n items.`

I am not sure why the two DescribeCoverage requests are invoked in the same test.  We can see the test `wcs2:get-kvp-core-req21` 

https://github.com/opengeospatial/ets-wcs20/blob/e69aa97a57f678964c03995d0b08b831dac80148/src/main/scripts/ctl/DescribeCoverage.xml#L1110

The second DescribeCoverage request is failing due to the unsatisfied condition.

https://github.com/opengeospatial/ets-wcs20/blob/e69aa97a57f678964c03995d0b08b831dac80148/src/main/scripts/ctl/DescribeCoverage.xml#L1149


Can you please look into this condition of test?

**Comment by lgoltz** [comment]
## Requirement 21
```
Requirement 21 /req/core/describeCoverage-response-list-size:
The response to a successful DescribeCoverage request with n coverage identifiers shall
contain a CoverageDescriptions element consisting of n CoverageDescription
items as specified in Figure 8 and Table 12.
```

`wcs2:get-kvp-core-req21` has two subtests, the first requests all Coverages (this is described in _A.1.21
DescribeCoverage returns information on all coverages requested_), the second test requests two Coverages.
I think the second test can be removed. Another option would be to skip the test `wcs2:req21`.

## Requirement 22
```
Requirement 22 /req/core/describeCoverage-response-contents:
The response to a successful DescribeCoverage request containing n identifiers id 1 , ..., id n
shall contain, for each identifier id i passed (1≤ i ≤ n ), a wcs:coverageDescription
consisting of the metadata of the coverage identified by id i , that is: the complete
wcs:CoverageOffering minus the coverage rangeSet .
Dependency: http://www.opengis.net/spec/GMLCOV/1.0/conf/gml-coverage
```

Requirement 22 includes the option that the number of provided Coverages is 1. I think the test should be adapted to handle this case correctly (should be done by removing the second part of the test).

**Comment by lgoltz** [comment]
Successfully tested with http://ows.eox.at/cite/mapserver?service=wcs&version=2.0.1&request=getcapabilities Tests are successful.

We should think about skipping tests which requires more than one coverage when the service provides only one coverage (new issue created: #79).
