### ISSUE TITLE
Document result form version  1.11 and 1.12

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wcs20#39]
Want to be sure that the new revision did not introduced new bugs

**Comment by bermud** [comment]
Results have been documented here: https://github.com/opengeospatial/ets-wcs20/wiki/WCS-2.0-Reference-Implementations-Test-results

**Comment by dstenger** [comment]
@bermud 
Are further actions required?
Otherwise, the issue can be closed.

**Comment by bermud** [comment]
I see that the behavior is similar for 1.11 and 1.12. Good to close.
