### ISSUE TITLE
Update CTL with better information about conformance classes 

### ISSUE THREAD

**Issue by keshav-nangare** [opengeospatial/ets-wcs20#42]
The test needs to be updated to better provide information about the grouping of the conformance class and determination about which ones are the basic conformance classes needed for certification.

Changes that are required are described here:

https://github.com/opengeospatial/cite/wiki/Encoding-Conformance-Classes

**Comment by lgoltz** [comment]
From WCS 2.0 specification:

```
2 Conformance
Standardization target are WCS 2.0 implementations (currently: servers).
This document establishes a single requirements class, core, of
http://www.opengis.net/spec/WCS/2.0/req/core with a single pertaining conformance 
class, core, with URI http://www.opengis.net/spec/WCS/2.0/conf /core. Requirements 
and conformance test URIs defined in this document are relative paths to be 
appended to http://www.opengis.net/spec/WCS/2.0/. 
Annex A lists the conformance tests which shall be exercised on any software 
artefact claiming to implement an OGC WCS.
```

I think the complete conformance class must be configured as `conformance class` and `basic`. This should be the test `wcs2:main_test` which is executed if `Core` is executed. 
https://github.com/opengeospatial/ets-wcs20/blob/157d04f3bd6a7494ee16924dc34ff14ffa28ea62/src/main/scripts/ctl/wcs2main.xml#L104

**Comment by lgoltz** [comment]
Implemented as proposed in https://github.com/opengeospatial/ets-wcs20/issues/42#issuecomment-357905688: PR #66
