### ISSUE TITLE
Scale extension is wrong for scaleByFactor in test script

### ISSUE THREAD

**Issue by bangph** [opengeospatial/ets-wcs20#43]
The WCS standard OGC 12-039 states:

> Requirement 5 getCoverage-scale-by-factor-positive:
The Scal::scaleByFactor parameter in a GetCoverage? request, if present, shall have a
positive float value.
Note A value of 1.0 leaves the coverage unscaled, a value between 0 and 1 scales down (reduces target domain), a value greater than 1 scales up (enlarges target domain).

However, in test script a scalebyfactor (e.g: scaleByFactor=4) > 1 scales down (size reduced) and < 1 (e.g: scaleByFactor=0.25) scales up (size increased), which is wrong.

It seems to happen on req13 of https://github.com/opengeospatial/ets-wcs20/blob/master/src/main/scripts/ctl/ext_get-scal.xml

> 
	<ctl:test name="wcs2:get-scal-req13">
		<ctl:param name="GetCoverage"/>
		<ctl:param name="DescribeCoverage"/>
		<ctl:assertion>Req13:Test scale-axes-by-factor result.</ctl:assertion>
		<ctl:code>
			<xsl:if test="not(floor(number(tokenize(string($DescribeCoverage//*[local-name()='domainSet']//*[local-name()='GridEnvelope']/*[local-name()='high']),'\s+')[1]) div 2) = number(tokenize(string($GetCoverage//*[local-name()='domainSet']//*[local-name()='GridEnvelope']/*[local-name()='high']),'\s+')[1] ))">
				<ctl:message>[FAILURE] The scal result is not correct.</ctl:message>
				<ctl:fail/>
			</xsl:if>
		</ctl:code>
	</ctl:test>

**Comment by lgoltz** [comment]
Thanks for reporting this. 

The test checks if the high of DescribeCoverage divided by 2 equals the high of GetCoverage. As you already said this should be the case if the original coverage is scaled down. The scaleByFactor in the GetCoverage request should be 0.5 in this case. 

There are three tests this test is called:
 * wcs2:get-scal-req19-22: GET request with SCALEAXES of 2.0 (both axis)
 * wcs2:get-scal-req24: POST with ScaleAxesByFactor of 2.0 (both axis)
 * wcs2:get-scal-req23: GetCoverage1 is not specified

I agree with your analysis. Furthermore the test wcs2:get-scal-req23 is faulty regarding the definition of variables.

Can you provide a service URl for testing?

```
not(
  floor(
    number(
      tokenize(
        string($DescribeCoverage//*[local-name()='domainSet']//*[local-name()='GridEnvelope']/*[local-name()='high']),
        '\s+'
      )[1]
    ) div 2
  ) 
  = 
  number(
    tokenize(
      string($GetCoverage//*[local-name()='domainSet']//*[local-name()='GridEnvelope']/*[local-name()='high']),
      '\s+'
    )[1] 
  )
)
```

**Comment by bangph** [comment]
@lgoltz : thanks for quick response. We also have this faulty implementation in our system so we need to update first. For a long time, I could not contact to Jin Song Di, do you know he is still working for CITE? As I really need his support as I am working on rasdaman project which he worked few years ago, and we want to solve some issues from existing WCS extensions and want to implement new test suites for WCS extensions.

**Comment by lgoltz** [comment]
@bangph From the commit history it seems he is inactive since more than one year. We will clarify this. If he does not work on CITE any longer, we will try to fix this issue as soon as possible.

**Comment by bangph** [comment]
@lgoltz: I updated our implementation for WCS 2.0.1 Scaling extension to this endpoint http://moon.planetserver.eu:8084/rasdaman/ows

and after that, it will fail only with 

` Test wcs2:get-scal-req13 (View Details): Failed`

so you could update the test script easily from "div" to "mul"? BTW, do you have a newer version of OGC CITE CTL language? I could find this old one https://portal.opengeospatial.org/files/?artifact_id=33085  (but could not found the "div" operator in this document).

FYI: I'm working for Prof. Dr. Peter Baumann in rasdaman project and he is the creator of all WCS 2.0.1 extensions and as Jin Song Di is out of contact, he wants to implement test suites for WCPS (http://portal.opengeospatial.org/files/?artifact_id=32314&passcode=8trkf8nkchqpkn0ywu5c) and WCS-Transaction (http://docs.opengeospatial.org/is/13-057r1/13-057r1.html).

 I'm not capable of doing it yet (I've no experience about CITE's abilities and writing CTL test suites),  but, if we don't have a better choice (i.e: Jin Song Di is never working with CITE anymore), so I will have to do it but I'm not a CITE's employee to get internal support when writing test suites and have problems (either with CTL or CITE's capabilities)..

Please ask Dr. Luis Bermudez about what is the best way in these cases (CITE will support us to write test suites by sharing your experience/expertise ?)

**Comment by lgoltz** [comment]
Thanks for reporting the URl. I tried to reproduced the problem with the official team engine [1] and the provided WCS [2]. I've selected all conformance classes (WCS Scaling 1.0 should be fine, too). The test is not executed. I assume the problem is that in the capabilities the DCP URLs  points to a local endpoint (http://localhost:8084/rasdaman/ows). Can you check this?

We will provide a fix with the next release. The "div" operator is not part of CTL, but of XPath. That's why it is not explained in the documentation of CTL.

We will forward your question concerning support to write test suites to Luis. 

[1] http://cite.opengeospatial.org/teamengine
[2] http://moon.planetserver.eu:8084/rasdaman/ows?service=WCS&request=GetCapabilities&acceptversions=2.0.1

**Comment by bangph** [comment]
@lgoltz: I could run the test with http://cite.opengeospatial.org/teamengine for only WCS 2.0.1 Scaling Extension, you need to open Web Browser Console (F12) and remove the checked checkbox for WCS 2.0.1 core which should not be run (See the attached image). This is kind of a hack but our server is not supposed to run WCS Core test when it shouldn't.

So the problem with the DCP is not related here. Attachment is a log file for the test session I've just run and failed only with  Test wcs2:get-scal-req13 (View Details): Failed.
![screenshot from 2017-10-30 12-59-17](https://user-images.githubusercontent.com/6914451/32169792-3c157958-bd72-11e7-8836-0d8c693d3cf1.png)

[s0081.zip](https://github.com/opengeospatial/ets-wcs20/files/1427068/s0081.zip)

Thanks for the "div" in XPath, it is out of my knowledge.

**Comment by lgoltz** [comment]
@bangph  With this workaround I can reproduce the failure. Thanks!

**Comment by lgoltz** [comment]
@bangph Can you reactivate the service for testing?

**Comment by bangph** [comment]
@lgoltz yes, it is on again: http://moon.planetserver.eu:8084/rasdaman/ows
