### ISSUE TITLE
Rework test wcs2:post-xml-req2 (post/xml)

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wcs20#54]
## Setup
SUT: TODO
Selected CCs: all, except _WCS WPS 2.0 (Processing)_
Tested locally with docker environment 
  * ETS WCS 2. 0 1.13-SNAPSHOT 
 * TEAM Engine 5.2-SNAPSHOT

## Testfailure
"[FAILURE] ows:Constraint element for XML POST is not included in the OperationsMetadata element"
 *  Implementation of the test: https://github.com/opengeospatial/ets-wcs20/blob/157d04f3bd6a7494ee16924dc34ff14ffa28ea62/src/main/scripts/ctl/ext_post-xml.xml#L72-L100

## Details
* Requirement 2 from WCS 2.0 POST extension: 
```
Requirement 2 /req/post-xml/wcsServiceMetadata:
For those WCSServiceMetadata elements inherited from OWSServiceMetadata , the
following rules shall apply:
-
WCS servers shall specify the HTTP POST request encodings accepted by
including an ows:Constraint element, with “PostEncoding” as the value of the name
attribute and a value “XML” to indicate that XML encoding is allowed, but without SOAP
message encapsulation.
-
If the HTTP POST connect point URL is different for different encodings of the
operation requests, this ows:Constraint element shall be included in each POST element.
When the connect point URL is the same for all encodings of all operation requests, this
ows:Constraint element shall be included in the OperationsMetadata element.

```

## Proposal
 * Further investigations required

**Comment by lgoltz** [comment]
As far as I see is correct: The configured POST URLs are the same for each operation, so the  ows:Constraint element shall be included in the  OperationsMetadata element and not for each POST element.

**Comment by dstenger** [comment]
It was confirmed that analysis of lgoltz is correct.
Issue can be closed.
