### ISSUE TITLE
wcseo:get-kvp-req63-66 fails with InvocationTargetException (eowcs)

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wcs20#56]
## Setup
SUT: TODO
Selected CCs: all, except _WCS WPS 2.0 (Processing)_
Tested locally with docker environment 
  * ETS WCS 2. 0 1.13-SNAPSHOT 
 * TEAM Engine 5.2-SNAPSHOT

## Testfailure
" Error in call to extension function {public org.w3c.dom.NodeList com.occamlab.te.TECore.request(org.w3c.dom.Document,java.lang.String) throws java.lang.Throwable}: Exception in extension function java.lang.reflect.InvocationTargetException"
 *  Failure from error log: 
```
Caused by: java.lang.RuntimeException: Failed to parse resource from https://ogc.webgistesting.net/server/services/Mynetcdf/ImageServer/WCSServer?service=WCS&VERSION=2.0.1&request=DescribeEOCoverageSet&eoId=Mynetcdf, Mynetcdf_salinity, Mynetcdf_water_temp&count=100 
 Failed to parse input: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream
        at com.occamlab.te.parsers.XMLValidatingParser.parse(XMLValidatingParser.java:222)
        ... 164 more
```
* Request send by the ETS contains spaces in eoId parameter values: `eoId=Mynetcdf, Mynetcdf_salinity, Mynetcdf_water_temp`

## Proposal
 * Remove spaces or encode parameter (as in #45)

**Comment by lgoltz** [comment]
Fixed by removing the spaces in commit https://github.com/opengeospatial/ets-wcs20/commit/370acc074cf601dbefadb9d685604595027494cc

**Comment by dstenger** [comment]
Successfully tested.

Test wcseo:get-kvp-req63-66 is passed.
