### ISSUE TITLE
Clean up extension 'Interpolation'

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wcs20#62]
## Setup
SUTs: 
1. http://conformance.rasdaman.com/ows?service=WCS&request=GetCapabilities&acceptversions=2.0.1
1. http://ows.eox.at/cite/mapserver?service=wcs&version=2.0.1&request=getcapabilities

Selected CCs: only `interpolation`
Tested locally with docker environment 
  * ETS WCS 2. 0 1.13-SNAPSHOT (includes PR #48)
 * TEAM Engine 5.2

## Description
There are some test  for the extension 'Interpolation' (ext_get-int.xml)  which are never executed:
 * wcs2:get-int-req1
* wcs2:get-int-req2
* wcs2:get-int-req3
* wcs2:get-int-req4

## Tasks
 * [ ] Include or remove tests listed above.
 * [ ] Check  if the execution of the tests is fine. Only few of the existing (and included)  tests ate executed and listed in the result view.

**Comment by lgoltz** [comment]
> Include or remove tests listed above.

 Fixed with commit https://github.com/opengeospatial/ets-wcs20/commit/d8eb5c45f663191a2385055e284a37f068dba865

Test `wcs2:get-int-req4` requests all URLs provided in the Capabilities (InterpolationSupported) parses the response with an XMLValidatingParser.  The assertion checks if the length of the response is not 0.

Specification:
```
Requirement 4 interpolation/wcsServiceMetadata-interpolationMethods:
The interpolationSupported item(s) delivered in the ServiceMetadata element of the response 
to a successful GetCapabilities request shall consist of a pairwise distinct list of URLs.
```
I think the test should only check if the content of all interpolationSupported item are valid URLs.


> Check if the execution of the tests is fine. Only few of the existing (and included) tests ate executed and listed in the result view.

Test looks fine, except that the all test (except those included before) should be executed only if DescribeCoverage exists. Fixed with commit https://github.com/opengeospatial/ets-wcs20/commit/80e52999153b44c4aad55051e10da14b6fa66744



The two test services are currently not useful:
 1. GetCoverage is not valid
 2. Does not provide a Coverage with BoundingBox/@dimensions=2 (expected by the ETS)

**Comment by dstenger** [comment]
Successfully tested.

Following tests are executed:
* wcs2:get-int-req1
* wcs2:get-int-req2
* wcs2:get-int-req3
