### ISSUE TITLE
DescribeCoverage test fails with validation failure 

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wcs20#64]
## Setup
SUT: http://conformance.rasdaman.com/ows?service=WCS&request=GetCapabilities&acceptversions=2.0.1
Selected CCs: Core , Post
Tested locally with docker environment 
  * ETS WCS 2.0 1.13
 * TEAM Engine 5.2

## Testfailure
Several test fails due to an Validation error (e.g. wcs2:get-kvp-core-req21):

```
  cvc-complex-type.2.4.b: The content of element 'gmlcov:metadata' is not complete. One of '{WC[##other:"http://www.opengis.net/gmlcov/1.0"]}' is expected.
Validation error:
  cvc-complex-type.2.4.a: Invalid content was found starting with element 'gmlcov:Extension'. One of '{WC[##other:"http://www.opengis.net/gmlcov/1.0"]}' is expected.
2 validation errors detected.
```

**Comment by lgoltz** [comment]
Tests fails since merge of pull request #46 cause the gmlcov schema dependencies are outdated.

**Comment by dstenger** [comment]
Test with http://conformance.rasdaman.com/ows?service=WCS&request=GetCapabilities&acceptversions=2.0.1 successful.

The schema validation errors in e.g. wcs2:get-kvp-core-req21 do not occur any more.
