### ISSUE TITLE
Reference Implementation is Failing with TE 4.3

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wcs20#7]
RI has been tested with TEAM Engine 4.0.1 with the default libs and the WCS 2.0 test v r1.8.  But with the current beta (4.3) is not passing.

 <parsers:HTTPParser> is not parsing the PNG result

Link to RI: http://kahlua.eecs.jacobs-university.de:8080/petascope_wcs2

Maybe we need to update the parsers?

**Comment by aashishlodha** [comment]
While executing the WCS2.0 test, in the phase where code validates **wcsAll.xsd**,  some initial requests which were returning the xml content got parsed successfully, but in one request it returned the **PNG** image, and it didn't got parsed with **'XMLValidatigParser'**. Following is the URI of that request,

http://kahlua.eecs.jacobs-university.de:8080/petascope_wcs2?SERVICE=WCS&VERSION=2.0.1&REQUEST=ProcessCoverages&query=for c in ( mean_summer_airtemp ) return  encode (c,"png")

As per the **Jin's** suggestion we tried with the **ImageParser** for PNG image request (in wcs_2_suite.xml), but we getting 505 error in UI test's **"View_Details"** section as following:

Method: get
   URL: http://kahlua.eecs.jacobs-university.de:8080/petascope_wcs2?SERVICE=WCS&VERSION=2.0.1&REQUEST=ProcessCoverages&query=for c in (mean_summer_airtemp) return  encode (c,"png")

   Response from parser parsers:HTTPParser:
      <response>
   <status code="505" protocol="HTTP/1.1">HTTP Version Not Supported</status>
   <headers>
      <header name="Server">Apache-Coyote/1.1</header>
      <header name="Date">Thu, 22 Oct 2015 11:55:18 GMT</header>
      <header name="Connection">close</header>
   </headers>
   <content/>
   </response>

Message d68e110_1:
   

Message d68e117_1:
   [FAILURE] The result should be a png image

Result: Failed

**Comment by jinsongdi123** [comment]
http://kahlua.eecs.jacobs-university.de:8080/petascope_wcs2?SERVICE=WCS&VERSION=2.0.1&REQUEST=ProcessCoverages&query=for c in (mean_summer_airtemp) return encode (c,"png") 
returns a png via browser. The http code is 200 OK. (Tested by Fiddler)

However, below ctl request returns "HTTP/1.1 505 HTTP Version Not Supported"

               <ctl:url>
                  <xsl:value-of select="$url"/>
               </ctl:url>
               <ctl:method>get</ctl:method>
               <ctl:param name="SERVICE">WCS</ctl:param>
               <ctl:param name="VERSION">2.0.1</ctl:param>
               <ctl:param name="REQUEST">ProcessCoverages</ctl:param>
               <ctl:param name="query">for c in ( <xsl:value-of select="$CoverageId"/> ) return  encode    (c,"png") </ctl:param>

It seems that the generated http request is not accepted by Host: kahlua.eecs.jacobs-university.de:8080

**Comment by aashishlodha** [comment]
We also need to investigate the 'Accept' header of request we make in code, in browser if we type following URL, 
_http://kahlua.eecs.jacobs-university.de:8080/petascope_wcs2?SERVICE=WCS&VERSION=2.0.1&REQUEST=ProcessCoverages&query=for c in (mean_summer_airtemp) return encode (c,"png")_

it will be 'text/html' by default, but you look into the 'Network' tab (of browser's console) for this request's response, its a binary stream.

But if you look at the Google's homepage, the main logo image request have response as actual image, not a byte stream of image.

**Comment by aashishlodha** [comment]
@Keshav: Please check that the URL is getting encoded or not while making request to the server. Like Chrome replaces spaces in URL with %20; Java may be doing this while sending request out. If it replaces spaces, then it will not return  the image file.

**Comment by aashishlodha** [comment]
@Keshav: Please check the request and response log for PNG file request we are making. Please use tools like Fiddler to record the Network log, and examine the PNG request/response.

**Comment by keshav-nangare** [comment]
1. I have tried with the fiddler tool to get all the request and reponse. 
By using this tool we found the PNG request get returned the 505 response, following is the request and response in fiddler:-


	Request in fiddler:
	-------------------------------------------------------------------------------------------------------------------
	GET http://kahlua.eecs.jacobs-university.de:8080/petascope_wcs2?SERVICE=WCS&VERSION=2.0.1&REQUEST=ProcessCoverages&query=for C IN ( MEAN_SUMMER_AIRTEMP ) RETURN  ENCODE (C,"PNG") HTTP/1.1

	Cache-Control: no-cache
	Pragma: no-cache
	User-Agent: Java/1.7.0_79
	Host: kahlua.eecs.jacobs-university.de:8080
	Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
	Connection: keep-alive
	----------------------------------------------------------------------------------------------------------------------

	Response in Fiddler:
	----------------------------------------------------------------------------------------------------------------------
	HTTP/1.1 505 HTTP Version Not Supported
	Server: Apache-Coyote/1.1
	Date: Mon, 26 Oct 2015 14:23:14 GMT
	Connection: close
	----------------------------------------------------------------------------------------------------------------------

2. Then I encoded the original URL (query param was having spaces), it didn't give the 505 this time, but ImageParser failed to parse that image.
	(http://kahlua.eecs.jacobs-university.de:8080/petascope_wcs2?SERVICE=WCS&VERSION=2.0.1&REQUEST=ProcessCoverages&query=for C IN ( MEAN_SUMMER_AIRTEMP ) RETURN  ENCODE (C,"PNG"))
	**Encoded to:**
	http://kahlua.eecs.jacobs-university.de:8080/petascope_wcs2?SERVICE=WCS&VERSION=2.0.1&REQUEST=ProcessCoverages&query=for%20c%20in%20%28mean_summer_airtemp%29%20return%20%20encode%20%28c,%22png%22%29

3. After that I hardcoded the URL (in ext_get-proc.xml) to point to another PNG image which Jin was pointing to in his draft and executed the test again, it was not giving 505 error, but ImageParser failing to parse that image. While Debugging the code at runtime, it was throwing error in parsing step, it was catched in Java 'catch' block, but it was showing the test cases as Passed.

	**URL used:** http://pic23.nipic.com/20120820/10076261_131855310174_2.png

**Comment by keshav-nangare** [comment]
Hi,

Here is some problem with the image-parser:

In one request server returned the image and I have used the image parser to parse that image to check the returned image is PNG or not.

But image-parser failed to parse this image (The exception is "Failed to parse multipart/x-mixed-replace; boundary=End resource from file:/home/keshav/CATALINA_BASE/temp/$te_4966216358531816169.tmp"). 

Follwoing is the ctl request:
Is this request is correct or not to check the format of image?

--------------------------------------------------------------------

                            
                                
                                  
                                <ctl:request>
                                 <ctl:url> http://kahlua.eecs.jacobs-university.de:8080/petascope_wcs2</ctl:url>
                                <ctl:method>get</ctl:method>
                                <ctl:param name="SERVICE">WCS</ctl:param>
                                <ctl:param name="VERSION">2.0.1</ctl:param>
                                <ctl:param name="REQUEST">ProcessCoverages</ctl:param>		
                                <ctl:param name="query">for%20c%20in%20%28%20mean_summer_airtemp%20%29%20return%20%20encode%20%28c,%22png%22%29 </ctl:param>
                                <parsers:HTTPParser>
                                    <parsers:parse>
                                        <parsers:ImageParser>
                                            <parsers:type />
                                        </parsers:ImageParser>
                                    </parsers:parse>
                                </parsers:HTTPParser>
                            </ctl:request>
			
--------------------------------------------------------------------------

or

http://kahlua.eecs.jacobs-university.de:8080/petascope_wcs2?SERVICE=WCS&VERSION=2.0.1&REQUEST=ProcessCoverages&query=for%20c%20in%20%28%20mean_summer_airtemp%20%29%20return%20%20encode%20%28c,%22png%22%29

How we can check the image format using the ctl request?

**Comment by rjmartell** [comment]
The request may specify a request header if desired. For example:
```
<ctl:method>GET</ctl:method>
<ctl:header name="Accept">image/*</ctl:header>
...
```

Since the `<parsers:type />` config element appears under parsers:ImageParser, the summary info returned by the image reader should report the actual media type of the response (it may only report the media subtype, e.g. "png").

**Comment by rjmartell** [comment]
Note that the `ImageParser` is chained to the `HTTPParser`. The parse result should look something like the following (I checked it by retrieving [this test image](http://www.fnordware.com/superpng/pnggrad16rgb.png)):
```xml
<response>
  <status code="200" protocol="HTTP/1.1">OK</status>
  <headers>
    <header name="Date">Fri, 20 Nov 2015 16:47:19 GMT</header>
    <header name="Server">Apache/1.3.34 (Debian) mod_ssl/2.8.25 OpenSSL/0.9.8c</header>
    <header name="Last-Modified">Thu, 03 Oct 2002 09:38:40 GMT</header>
    <header name="Content-Length">3974</header>
    <header name="Content-Type">image/png</header>
  </headers>
  <content>
    <ctlp:ImageParser xmlns:ctlp="http://www.occamlab.com/te/parsers">
      <ctlp:type>png</ctlp:type>
    </ctlp:ImageParser>
  </content>
  <!--Response received in [737] milliseconds-->
</response>
```

The Content-Type header is already collected by the HTTPParser so the ImageParser adds nothing in this case.

**Comment by rjmartell** [comment]
Regarding test `wcs2:get-proc-req8-10` (in ext_get-proc.xml), "Check that the result is correct" is not a testable assertion. What exactly is expected here? Just any image in the entity-body?

**Comment by jinsongdi123** [comment]
Indeed, the result shall be a multipart coverage or a pure png image as indicated by OGC09-146r2 req35 .
When TE generates a valid image request, it shall return '200 OK' instead of '505 HTTP Version Not Supported',as below:

Request d1e64_1:
   Method: get
   URL: http://kahlua.eecs.jacobs-university.de:8080/petascope_wcs2?SERVICE=WCS&VERSION=2.0.1&REQUEST=ProcessCoverages&query=for c in (mean_summer_airtemp) return  encode (c,"png")
   Response from parser parsers:HTTPParser:
      <response>
   <status code="505" protocol="HTTP/1.1">HTTP Version Not Supported</status>
   <headers>
      <header name="Server">Apache-Coyote/1.1</header>
      <header name="Date">Mon, 23 Nov 2015 07:32:08 GMT</header>
      <header name="Connection">close</header>
   </headers>
   <content/>
   </response>

 <ctl:header name="Accept">image/*</ctl:header> returns 505 in this test.

**Comment by jinsongdi123** [comment]
The CTL will invoke HTTPParser, then the ImageParser for the pure image result.
