### ISSUE TITLE
Create SoapUI tests and integrate them into Maven and Jenkinsfile

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wcs20#71]
See opengeospatial/ets-wms13#56 for instructions.

Please use following service implementation: http://ows.eox.at/cite/mapserver?service=WCS&version=2.0.1&request=GetCapabilities

**Comment by keshav-nangare** [comment]
The ets-wcs20 is based on the CTL so we can't execute this test-suite through the REST api.

**Comment by keshav-nangare** [comment]
Fixed with this PR #74.

**Comment by dstenger** [comment]
Must be postponed till TEAM Engine 5.4 is released and installed on beta (see https://github.com/opengeospatial/ets-wcs20/pull/73).

**Comment by dstenger** [comment]
@keshav-nangare Can you please adjust the pull request to new version of REST interface not having version number in path?

**Comment by keshav-nangare** [comment]
@dstenger 

Updated the PR with the SoapUI project and removed the version parameter from the URI.

Fixed with this commit: adbd63957250c4ca9a1afe356cf5096903f7495b

**Comment by dstenger** [comment]
@keshav-nangare 
Can you please also add integration tests as described in https://github.com/opengeospatial/cite/wiki/How-to-run-tests-for-test-suites-with-SoapUI?
You can use following command to verify the integration tests: `mvn clean verify -Pintegration-tests`

**Comment by keshav-nangare** [comment]
@dstenger 

I have added an integration test and updated Jenkins's file according to documentation. The changes are verified with this command `mvn clean verify -Pintegration-tests`.
