### ISSUE TITLE
Enable test execution using a RESTful API

### ISSUE THREAD

**Issue by keshav-nangare** [opengeospatial/ets-wcs20#72]
Create interface to execute CTL test-suite using RESTful API.

Reference: https://github.com/opengeospatial/ets-wms13/issues/34

**Comment by keshav-nangare** [comment]
The wcs20 has its own local resources(schema's) and the parser is trying to load schema from local resource but it failed with following error:

------------------------------------------------
Caused by: java.lang.RuntimeException: Failed to parse resource from http://ows.eox.at/cite/mapserver?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCapabilities 
 schema_reference.4: Failed to read schema document 'file:/C:/CATALINA_BASE/bin/file:/C:/TE_BASE/resources/lib/ets-wcs20-1.15-SNAPSHOT.jar!/wcs/2.0/wcsAll.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
	at com.occamlab.te.parsers.XMLValidatingParser.parse(XMLValidatingParser.java:227)
	... 102 more

------------------------------------

Can you please provide me some pointers? why the class loader is referring the two paths i.e. catalina_base/bin and te_base/resource? Do you have any idea about it?

**Comment by lgoltz** [comment]
@keshav-nangare 
Is  https://github.com/opengeospatial/ets-wcs20/tree/feature-issue%2372 the branch you are working on? Contains the branch all changes? 
When does the failure occur (can you provide the URL)?

**Comment by lgoltz** [comment]
@keshav-nangare 
The problem is that the resource from the jar file is handled as file in https://github.com/opengeospatial/teamengine/blob/c6310f25f2a9f00fe57c6ef56f6d2d9c91a8f74a/teamengine-core/src/main/java/com/occamlab/te/parsers/XMLValidatingParser.java#L96

Using the URL instead of  `new File(url.getFile();` should fix the problem. A better solution would be to use a stream (cl.getResourceAsStream()) but the implementation is more complex, so I think using the URL is fine.

**Comment by keshav-nangare** [comment]
@lgoltz 

I did the implementation using URL and able to execute test-suite as expected. Currently I am testing the webapp with the same RI whether these changes are working or not. I will update you regarding this.

Thanks Lyn for your inputs!!

**Comment by keshav-nangare** [comment]
@lgoltz 

The ets-wcs20 test-suite is tested with the teamengine webapp and it worked fine.

After updating the URL logic, the teamengine-core JUnit test is failing and it expects the file not the URL type.
https://github.com/opengeospatial/teamengine/blob/c6310f25f2a9f00fe57c6ef56f6d2d9c91a8f74a/teamengine-core/src/test/java/com/occamlab/te/parsers/XMLValidatingParserTest.java#L47

I am not aware this test-case and why it expecting the file instance?

Do you have any idea about it? or should I update this test with the URL instance?

**Comment by lgoltz** [comment]
> Do you have any idea about it? or should I update this test with the URL instance?

I think you can update the test. It is improbably that the schema instance is used directly (and not favoured).
