### ISSUE TITLE
Test  wcseo:req6 does not accept gml:EnvelopeWithTimePeriod

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wcs20#78]
Test `wcseo:req6` is failing when following response is returned by DescribeCoverage request:
```
...
    <gml:boundedBy>
      <gml:EnvelopeWithTimePeriod srsName="http://www.opengis.net/def/crs/EPSG/0/4326" axisLabels="y x StdTime StdZ " uomLabels="Degree Degree Hours Meter " srsDimension="4">
        <gml:lowerCorner>1 1 1 1 </gml:lowerCorner>
        <gml:upperCorner>2 2 2 2 </gml:upperCorner>
        <gml:beginPosition>2019-01-01T00:00:00Z</gml:beginPosition>
        <gml:endPosition>2019-01-01T21:00:00Z</gml:endPosition>
      </gml:EnvelopeWithTimePeriod>
    </gml:boundedBy>
...
```

The test checks if gml:boundedBy contains gml:Envelope.

Thus, specification has to be checked whether gml:EnvelopeWithTimePeriod is fine as well.

**Comment by lgoltz** [comment]
Requirement 6 out of the Web Coverage Service 2.0 Interface Standard - Earth Observation Application Profile:

```
Requirement 6 /req/eowcs/footprint-inside-boundedBy:
In EOWCS::ReferenceableEOCoverage and EOWCS::RectifiedEOCoverage
instances, all polygons listed in eop:EarthObservation/om:featureOfInter-
est/eop:Footprint element shall be geometrically contained in the bounding box of
the gml:boundedBy element of the gml:Envelope.
```

gml:boundedBy references gml:Envelope and gml:EnvelopeWithTimePeriod substitutes gml:Envelope, s. http://schemas.opengis.net/gml/3.2.1/feature.xsd

The example above is schema conform. In my opinion this is a failure in the ets.

**Comment by keshav-nangare** [comment]
Added fix for gml:EnvelopeWithTimePeriod element with this commit:  2ca8187bd264b2f1a70dbb03c107c4d1b11172b1
