### ISSUE TITLE
url encoding of '+' sign in GetCoverage request

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wcs20#8]
When running cite tests for WCS 2.0.1, there is an error for test wcs2:get-kvp-core-req1-9.
when this request is send
http://<wcsurl>?service=WCS&VERSION=2.0.1&request=GetCoverage&CoverageId=C0017&format=application/gml+xml

last elements are not correct, the '+' sign is not url encoded. it should be gml%2Bxml

**Comment by jinsongdi123** [comment]
Thanks, The ctl is updated accordingly.

**Comment by coim32** [comment]
you change was not correct.
change should apply on get request parameters, you applied for post requests.
for example line 326 of DataModel.xml

**Comment by jinsongdi123** [comment]
Thanks, the ctl is updated accordingly
