### ISSUE TITLE
Why is wcs2:crs-req1 failing?

### ISSUE THREAD

**Issue by pomakis** [opengeospatial/ets-wcs20#84]
I'm trying to run "https://onestop.cubewerx.com/cubewerx/citeWcs201.cgi" through the Web Coverage Service (WCS) 2.0.1 CITE tests (version 1.12), and one of the tests it's failing is "wcs2:crs-req1", which tests the requirement:

Requirement 1 crs/extension-identifier:
A WCS service implementing conformance class crs of this CRS Extension shall include the following URI in the Profile element of the ServiceIdentification in a GetCapabilities response:
http://www.opengis.net/spec/WCS_service-extension_crs/1.0/conf/crs

The ServiceIdentification section in the capabilities document of the abovementioned WCS 2.0.1 server declares the following profiles:

```
    <Profile>http://www.opengis.net/spec/WCS/2.0/conf/core</Profile>
    <Profile>http://www.opengis.net/spec/WCS_protocol-binding_get-kvp/1.0/conf/g
et-kvp</Profile>
    <Profile>http://www.opengis.net/spec/WCS_service-extension_crs/1.0/conf/crs<
/Profile>
    <Profile>http://www.opengis.net/spec/WCS_service-extension_crs/1.0/conf/crs-
gridded-coverage</Profile>
    <Profile>http://www.opengis.net/spec/WCS_service-extension_scaling/1.0/conf/
scaling</Profile>
    <Profile>http://www.opengis.net/spec/GMLCOV/1.0/conf/gml-coverage</Profile>
    <Profile>http://www.opengis.net/spec/GMLCOV/1.0/conf/special-format</Profile
>
    <Profile>http://www.opengis.net/spec/GMLCOV_geotiff-coverages/1.0/conf/geoti
ff-coverage</Profile>
```
Yet the test fails, indicating:

Message d97e331_1:
   [FAILURE] The result should contain a http://www.opengis.net/spec/WCS_service-extension_crs/1.0/conf/crs

Why is this?  Is this an issue with the test, or with the way this server declares its profiles?

**Comment by dstenger** [comment]
Thank you for reporting. We will do further investigation.

**Comment by keshav-nangare** [comment]
The test is failing due to the extra parameter `DATASTORE` in the service URL.

https://demo.cubewerx.com/cubewerx/cubeserv/cite_wcs201?DATASTORE=Foundation&SERVICE=WCS&REQUEST=GetCapabilities&VERSION=2.0.1

**Comment by lgoltz** [comment]
In https://github.com/opengeospatial/ets-wcs20/blob/master/src/main/scripts/ctl/wcs2suite.xml the url is passed to the starting test `wcs2:main`. In this test the url is truncated  (https://github.com/opengeospatial/ets-wcs20/blob/c5de764488f9b1a0bccecf0a4eccef9be891aa5d/src/main/scripts/ctl/wcs2main.xml) and the url (before the '?') passed to the tests, where the capabilities are requested. 
The test `wcs2:main` should request the capabilities first and select the capabilities url. Or, to avoid multiple GetCapabilities request, request the capabilities and pass them to the called tests.

**Comment by keshav-nangare** [comment]
@lgoltz 

I agree with you that the test should invoke the GetCapabilites request in `wcs:main ` test to avoid multiple GetCapabilities requests in subtests. But if other tests want to invoke the HTTP request then we have to pass the URL to subtest. If we are passing the URL to subtest then again the same problem will occur. Do you any other idea to fix this issue?

**Comment by lgoltz** [comment]
@keshav-nangare The GetCapabilities URL should be available in the Capabilities document (xpath like //OperationsMetadata/Operation[@name='GetCapabilities']/DCP/HTTP/Get/@xlink:href). Subtest should parse the capabailities and use this url for further requests.

**Comment by keshav-nangare** [comment]
Thanks Lyn for the inputs. I will update the test accordingly.

**Comment by keshav-nangare** [comment]
@lgoltz @dstenger 

Current service [1] is not supporting the `Post` OperationsMetadata. There are lots of tests that are using the request method as "POST" so the currently the service don't have the `POST` URL in its capability document. How we could add extra parameter in the request with method `POST`?

The test `wcs2:post-xml-req3` invoking the request with the method post but it will fail because of the absence of the `DATASTORE=Foundation`.

https://github.com/opengeospatial/ets-wcs20/blob/97c511ff476733e3a63b27b599a9e10f97d6c0db/src/main/scripts/ctl/ext_post-xml.xml#L106-L128

[1] https://demo.cubewerx.com/cubewerx/cubeserv/cite_wcs201?DATASTORE=Foundation&SERVICE=WCS&REQUEST=GetCapabilities&VERSION=2.0.1

**Comment by dstenger** [comment]
@keshav-nangare The service does not support POST encoding. So, such tests can be ignored.

**Comment by keshav-nangare** [comment]
@pomakis 

Can you please take look at the following comments?

The current service doesn't have the `<CrsMetadata>` element as it is required for the CRS extension.

```
Test wcs2:crs-req3 : Failed  [Reason: The result should contain a <CrsMetadata>. element]

Test wcs2:crs-req6 : Failed (InheritedFailure)
   Test wcs2:get-kvp-crs-req6 : Failed
            HTTP request returns a Gateway timeout error
            https://demo.cubewerx.com/cubewerx/cubeserv/cite_wcs201?DATASTORE=Foundation&&service=WCS&VERSION=2.0.1&request=GetCoverage&coverageid=etopo2&SUBSETTINGCRS=&OUTPUTCRS=&subset=Lat(-89.98333333333333,89.98333333333333)&subset=Long(-179.9833333333333,179.9833333333333)

Test wcs2:crs-req7 : Failed (InheritedFailure)
   Test wcs2:get-kvp-crs-req7 : Failed
             HTTP request returns a Gateway timeout error
             https://demo.cubewerx.com/cubewerx/cubeserv/cite_wcs201?DATASTORE=Foundation&&service=WCS&VERSION=2.0.1&request=GetCoverage&coverageid=etopo2&SUBSETTINGCRS=&subset=Lat(-89.98333333333333,89.98333333333333)&subset=Long(-179.9833333333333,179.9833333333333)

Same errors for following tests:
Test wcs2:crs-req8 : Failed (InheritedFailure)
   Test wcs2:get-kvp-crs-req8 : Failed
 Test wcs2:crs-req9 : Failed (InheritedFailure)
   Test wcs2:get-kvp-crs-req9 : Failed
``` 
If you observed the HTTP request there are two empty parameters `SUBSETTINGCRS` & `subset`. These parameters empty because the test expecting the element `<crsSupported>` after the `<CrsMetadata>`.

**Comment by pomakis** [comment]
The problem is that neither the official schema at http://schemas.opengis.net/wcs/crs/1.0/wcsCrs.xsd nor the accompanying example at http://schemas.opengis.net/wcs/crs/1.0/examples/responseGetCapabilities.xml have a `<CrsMetadata>` element.  They put the `<crsSupported>` element as an immediate child of the `<Extension>` element.  And so our server does the same.  I could adjust our server implementation to insert a `<CrsMetadata>` element, but then our GetCapabilities response document wouldn't be valid according to the schema.

I might make this change, at least temporarily, so that we can get past this test.  However, I think at least the following two actions should also be taken:

1. A change request must be made against OGC 11-053r1 to remove this inconsistency (either by removing the <CrsMetadata> element from the specification or by adding it to the schema).

2. The CITE test suite aught to accept both forms, because implementers could justifiably implement it either way (however much of an interoperability problem this unfortunately creates).  In fact, if it were to accept it only one way, I think it should honour the schema as trumping the wording in the specification.  After all, a service can't be considered valid if its output fails to validate against the schema.

**Comment by pebau** [comment]
Keith-
if you feel there is a problem with the standard (as it seems) you can file a change request, via official OGC mechanisms or just by email to me, sumamrising problem and maybe suggested remedy options. I bring it up during the next TC meeting.
-Peter

**Comment by pomakis** [comment]
Done (change request ID 580).

**Comment by dstenger** [comment]
@pomakis Is any action required for the test suite?

**Comment by pomakis** [comment]
Well, this test seems to pass in version 1.14 of the test suite, so I guess it's been resolved.  Thanks.
