### ISSUE TITLE
wrong version of ows in WCS GetCapabilities request

### ISSUE THREAD

**Issue by coim32** [opengeospatial/ets-wcs20#9]
line 316 of file  ets-wcs20/src/main/scripts/ctl/RequestBase.xml have wrong version of ows namespace
xmlns:ows="http://www.opengis.net/ows/1.1"
it should be 
xmlns:ows="http://www.opengis.net/ows/2.0"

**Comment by jinsongdi123** [comment]
Thanks. The ctl is updated accordingly
