### ISSUE TITLE
what is the expected response for Test wcs2:soap-core-req18

### ISSUE THREAD

**Issue by coim32** [opengeospatial/ets-wcs20#92]
my service generate the following response and the test fails, it looks to me like a correct soap error response 
`<?xml version='1.0' encoding='UTF-8'?>
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
  <soap:Body>
    <env:Fault xmlns:env="http://www.w3.org/2003/05/soap-envelope">
      <env:Code>
        <env:Value>env:Receiver</env:Value>
      </env:Code>
      <env:Reason>
        <env:Text>Server exception was encountered.</env:Text>
      </env:Reason>
      <env:Detail>
        <ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ows/2.0 http://schemas.opengis.net/ows/2.0/owsExceptionReport.xsd" version="2.0.1">
          <ows:Exception exceptionCode="InvalidEncodingSyntax" locator="wcs:Coverage">
            <ows:ExceptionText>Document received does not conform with protocol syntax.</ows:ExceptionText>
          </ows:Exception>
        </ows:ExceptionReport>
      </env:Detail>
    </env:Fault>
  </soap:Body>
</soap:Envelope>
`

**Comment by dstenger** [comment]
Thank you for reporting.
@keshav-nangare Can you please take a look at the reported behavior?

**Comment by keshav-nangare** [comment]
@coim32 

Can you please provide service to reproduce this issue?

**Comment by coim32** [comment]
you can use this one
http://150.136.177.253:8000/oraclespatial/wcs/wfs?service=WCS&VERSION=2.0.1&request=GetCapabilities

**Comment by coim32** [comment]
I can't keep the service running for much time, please do the tests asap

**Comment by keshav-nangare** [comment]
@dstenger 

I have investigated the issue and able to reproduce on my local machine but I did get the response as reported in the first comment. But I can see the failure is the same.

Please find below request and response for the test `wcs2:soap-core-req18`:
Request 
  URI: http://150.136.177.253:8000/oraclespatial/wcs/wfs
  Method: POST
  Body: 
```
<?xml version="1.0" encoding="UTF-8"?>
<soap-env:Envelope xmlns:soap-env="http://www.w3.org/2003/05/soap-envelope">
   <soap-env:Body>
      <wcs:DescribeCoverage xmlns:wcs="http://www.opengis.net/wcs/2.0" xmlns:ctl="http://www.occamlab.com/ctl" xmlns:ctlp="http://www.occamlab.com/te/parsers" xmlns:gen="java:com.occamlab.te.Generator" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:ows="http://www.opengis.net/ows/2.0" xmlns:saxon="http://saxon.sf.net/" xmlns:sch="http://purl.oclc.org/dsdl/schematron" xmlns:te="http://www.occamlab.com/te" xmlns:tec="java:com.occamlab.te.TECore" xmlns:tems="java:com.occamlab.te.web.MonitorServlet" xmlns:wcs2="http://www.opengis.net/wcs/2.0" xmlns:wcseo="http://www.opengis.net/wcseo/1.0" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" service="WCS" version="2.0.1" xsi:schemaLocation="http://www.opengis.net/wcs/2.0 http://schemas.opengis.net/wcs/2.0/wcsAll.xsd">
         <wcs:Coverage>C0007</wcs:Coverage>
      </wcs:DescribeCoverage>
   </soap-env:Body>
</soap-env:Envelope>

```
The test is expecting exception report and the response contains the same but parser is getting failed with below exception
```
<?xml version="1.0" encoding="UTF-8"?>
<response>
   <parser local-name="SOAPParser" namespace-uri="http://www.occamlab.com/te/parsers" prefix="ctlp">Validation error:&#xD;
  cvc-elt.1.a: Cannot find the declaration of element 'ows:ExceptionReport'.&#xD;
1 validation error detected.</parser>
   <content />
</response>
```

**Comment by coim32** [comment]
I figured out what was the problem, the response was a POST response instead of a SOAP response, I'll close the issue now, thanks.
