### ISSUE TITLE
several test of interpolatin extension does not appears in test result

### ISSUE THREAD

**Issue by coim32** [opengeospatial/ets-wcs20#93]
I just can see first 3 test but in log I found there are many more tests executed 
![image](https://user-images.githubusercontent.com/6456006/78413692-daf20780-75d5-11ea-9628-475ce932ace7.png)

**Comment by dstenger** [comment]
Thank you for reporting.
@keshav-nangare Can you please take a look at this?

**Comment by keshav-nangare** [comment]
Fixed with #96 PR

**Comment by coim32** [comment]
when does this change will be in the OGC teamengine online test suits?

**Comment by dstenger** [comment]
We will update the beta environment (https://cite.opengeospatial.org/te2/) in June.
